---
version: 1.0.0
files:
  README.md: Finder v%.%.%
  src/main/middleman/_footer.liquid: version v%.%.%
  package.json: ! '"version": "%.%.%"'
  bower.json: ! '"version": "%.%.%"'
  src/main/AndroidManifest.xml: android:versionName="v%.%.%"
